#!/command/with-contenv bash
# shellcheck shell=bash
set -e
ARGS=(-m "${SOLR_MEMORY}")

if [[ -n "${SOLR_JETTY_OPTS}" ]]; then
  ARGS+=(-j "${SOLR_JETTY_OPTS}")
fi

if [[ -n "${SOLR_JAVA_OPTS}" ]]; then
  ARGS+=(-a "${SOLR_JAVA_OPTS}")
fi

# When bind mounting we need to ensure that we
# actually can write to the folder.
chown -R solr:solr /opt/solr/server/solr

exec s6-setuidgid solr /opt/solr/bin/solr start -f "${ARGS[@]}"
