#!/usr/bin/with-contenv bash
set -e

# Only shutdown the container if this service was enabled otherwise ignore.
if [[ "${CONFD_ENABLE_SERVICE}" == "true" ]]; then
  s6-svscanctl -t /var/run/s6/services
fi
