version: "3.8"
services:
  ide:
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
    volumes:
      # Mount SSH agent so we can authenticate against github inside of the IDE container.
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
