#!/command/with-contenv bash
# shellcheck shell=bash
set -e

declare child
_term() {
  local signal=$(($? - 128))
  echo "Caught Signal: ${signal}"
  kill -TERM "$child" 2>/dev/null
  exit 15
}
trap "_term" SIGTERM

sleep 1000000 &
child=$!

wait "${child}"
