#!/command/with-contenv bash
# shellcheck shell=bash
set -e

# Only shutdown the container if this service was enabled otherwise ignore.
if [[ "${RIPRAP_CROND_ENABLE_SERVICE}" == "true" ]]; then
  # shellcheck disable=SC1091
  source /usr/local/share/s6/finish "${1}" "${2}"
else
  exec s6-svc -Od .
fi
