#!/usr/bin/with-contenv bash
set -e
ARGS=(-m "${SOLR_MEMORY}")

if [[ ! -z "${SOLR_JETTY_OPTS}" ]]; then
  ARGS+=(-j "${SOLR_JETTY_OPTS}")
fi

if [[ ! -z "${SOLR_JAVA_OPTS}" ]]; then
  ARGS+=(-a "${SOLR_JAVA_OPTS}")
fi

exec s6-setuidgid solr /opt/solr/bin/solr start -f "${ARGS[@]}"