#!/usr/bin/with-contenv bash
set -e

# Defines environment variables for use in other init scripts.
# It is generated by the 01-confd-render-templates.sh and its contents are
# expected to be overridden in child images.
/var/run/islandora/setup-environment.sh
