name: CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Setup Gradle Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Log in to Docker Hub
      run: docker login -u '${{ secrets.REGISTRY_USER }}' -p '${{ secrets.REGISTRY_PASS }}' '${{ secrets.REGISTRY_URL }}'
    - name: Enable buildkit
      shell: bash
      run: |
        echo '{"experimental": "enabled", "dns": ["8.8.8.8", "8.8.4.4"]}' > ~/.docker/config.json
    - name: Build Docker images
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build '-Prepository=${{ secrets.REPOSITORY }}' --info
    - name: Push Docker images
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: push '-Prepository=${{ secrets.REPOSITORY }}' '-PregistryUrl=${{ secrets.REGISTRY_URL }}' '-PregistryUsername=${{ secrets.REGISTRY_USER }}' '-PregistryPassword=${{ secrets.REGISTRY_PASS }}' --info
    # @todo add tests.
