name: run renovate

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * *'

jobs:
  run:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIV_KEY }}

      - name: run renovate
        env:
          BASE_BRANCH: ${{ github.event_name == 'schedule' && 'main' || github.ref_name }}
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # run renovate with our token
          # using branch set in workflow dispatch to allow testing PRs
          # see https://docs.renovatebot.com/configuration-options/#basebranches
          export RENOVATE_BASE_BRANCHES=$(jq -c -n --arg branch "$BASE_BRANCH" '[$branch]')
          echo "Running renovate against ${RENOVATE_BASE_BRANCHES}"
          docker run \
            --env LOG_LEVEL=debug \
            --env RENOVATE_ALLOWED_COMMANDS='["^bash ci/update-sha.sh .*$"]' \
            --env RENOVATE_PLATFORM=github \
            --env RENOVATE_REPOSITORIES=islandora-devops/isle-buildkit \
            --env RENOVATE_BASE_BRANCHES \
            --env RENOVATE_TOKEN \
            --rm \
            -v $(pwd):/usr/src/app \
            renovate/renovate
