name: 'Manage stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '47 18 * * *'
jobs:
  stale:
    uses: Islandora-Devops/.github/.github/workflows/stale.yaml@8266bc1a27cbfb4fe3663043303916019db5ea75 # main
    secrets: inherit
