name: 'Manage stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '47 18 * * *'
jobs:
  stale:
    uses: Islandora-Devops/.github/.github/workflows/stale.yaml@e350b16a04d4db031f22a5ebc0c3cf85deb1ffb6 # main
    secrets: inherit
