name: Test
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      digests:
        required: true
        type: string
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASSWORD:
        required: true
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # v6

      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          cache-read-only: false
          arguments: images:${{ inputs.image }}:test -Pisle.test.pull=true ${{ inputs.digests }} --info
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        if: always()
        with:
          name: ${{ inputs.image }} Test Logs
          path: build/**/*.log
